config/routes.rb
PodioRailsSample::Application.routes.draw do

  root :to => 'leads#index'
  resources :sessions, :only => [:new, :create] do
    collection do
      delete :destroy
      post :create_from_app_auth
    end
  end
  match "/auth/:provider/callback" => "sessions#create"
  resources :leads
  resources :tasks

end

app/models/lead.rb
class Lead < Podio::Item
  APP_ID = 12695955
  SPACE_ID = 3631649

  # Find all items in the Leads app
  def self.all
    collection = self.find_all(APP_ID)
    collection[:all]
  end

  # Find valid lead contacts in the space
  def self.space_contacts
    Podio::Contact.find_all_for_space(SPACE_ID, :order => 'contact', :limit => 12, :contact_type => 'space,connection', :exclude_self => false) rescue []
  end

  # Find valid sales contacts in the space
  def self.users
    Podio::Contact.find_all_for_space(SPACE_ID, :order => 'contact', :limit => 12, :contact_type => 'user', :exclude_self => false) rescue []
  end

  # Find valid statuses
  def self.statuses
    app = Podio::Application.find(APP_ID)
    field = app.fields.find { |field| field['external_id'] == 'status2' }
    field['config']['settings']['options'].map { |option| [option['text'], option['id']] }
  end

  def self.create_from_params(params)
    # raise fields.inspect
    self.create(APP_ID, { :fields => fields_from_params(params) })
  end

  def self.update_from_params(id, params)
    self.update(id, { :fields => fields_from_params(params) })
  end

  #
  # Map the field values return by the Podio API to simple getters
  #

  def organization
    field_values_by_external_id('company-or-organisation', :simple => true)
  end

  def lead_contact
    field_values_by_external_id('contacts', :simple => true).try(:[], 'name')
  end

  def sales_contact
    field_values_by_external_id('sales-contact', :simple => true).try(:[], 'name')
  end

  def potential_revenue_value
    field_values_by_external_id('potential-revenue').try(:first).try(:[], 'value').to_i
  end

  def potential_revenue_currency
    field_values_by_external_id('potential-revenue').try(:first).try(:[], 'currency')
  end

  def probability
    field_values_by_external_id('probability-of-sale', :simple => true)
  end

  def status_id
    field_values_by_external_id('status2', :simple => true).try(:[], 'id')
  end

  def status_text
    field_values_by_external_id('status2', :simple => true).try(:[], 'text')
  end

  def followup_at
    field_values_by_external_id('next-follow-up').try(:first).try(:[], 'start').try(:to_datetime)
  end

  protected

    def field_values_by_external_id(external_id, options = {})
      if self.fields.present?
        field = self.fields.find { |field| field['external_id'] == external_id }
        if field
          values = field['values']
          if options[:simple]
            values.first['value']
          else
            values
          end
        else
          nil
        end
      else
        nil
      end
    end

    def self.fields_from_params(params)
      {
        'company-or-organisation' => params[:organization],
        'contacts' => (params[:lead_contact].present? ? params[:lead_contact].to_i : nil),
        'sales-contact' => (params[:sales_contact].present? ? params[:sales_contact].to_i : nil),
        'potential-revenue' => { :value => params['potential_revenue_value'], :currency => params['potential_revenue_currency'] },
        'probability-of-sale' => params[:probability].to_i,
        'status2' => params[:status_id].to_i,
        'next-follow-up' => DateTime.new(params['followup_at(1i)'].to_i, params['followup_at(2i)'].to_i, params['followup_at(3i)'].to_i).to_s(:db)
      }.delete_if { |k, v| v.nil? }
    end

end

app/models/user.rb
class User < ActiveRecord::Base

  def self.create_with_omniauth(auth)
    create! do |user|
      user.provider = auth["provider"]
      user.uid = auth["info"]["user_id"]
      user.email = auth["info"]["email"]
    end
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery

  before_filter :ensure_login

  protected

    def ensure_login
      if session[:podio_access_token]
        init_podio_client
      else
        redirect_to new_session_path
      end
    end

    def init_podio_client
      Podio.setup(
        :api_url => 'https://api.podio.com',
        :api_key => ENV['PODIO_CLIENT_ID'],
        :api_secret => ENV['PODIO_CLIENT_SECRET'],
        :oauth_token => Podio::OAuthToken.new('access_token' => session[:podio_access_token], 'refresh_token' => session[:podio_refresh_token])
      )
    end
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  before_filter :load_collections, :only => [:new, :edit]

  def index
    @leads = Lead.all
  end

  def new
    @lead = Lead.new
  end

  def create
    Lead.create_from_params(params['lead'])
    redirect_to leads_path, :notice => 'Lead created'
  end

  def edit
    @lead = Lead.find_basic(params[:id])
  end

  def update
    Lead.update_from_params(params[:id], params['lead'])
    redirect_to leads_path, :notice => 'Lead updated'
  end

  def destroy
    Lead.delete(params[:id])
    redirect_to leads_path, :notice => 'Lead deleted'
  end

  protected

    def load_collections
      @lead_contacts = Lead.space_contacts
      @sales_contacts = Lead.users
      @statuses = Lead.statuses
    end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  skip_before_filter :ensure_login

  def new
  end

  def create
    auth = request.env["omniauth.auth"]
    user = User.find_by_provider_and_uid(auth["provider"], auth["info"]["user_id"]) || User.create_with_omniauth(auth)
    session[:user_id] = user.id
    session[:podio_access_token] = auth["credentials"]["token"]
    session[:podio_refresh_token] = auth["credentials"]["refresh_token"]
    redirect_to root_url, :notice => "Signed in!"
  end

  def create_from_app_auth
    Podio.setup(
      :api_url => 'https://api.podio.com',
      :api_key => ENV['PODIO_CLIENT_ID'],
      :api_secret => ENV['PODIO_CLIENT_SECRET']
    )

    Podio.client.authenticate_with_app(params[:app_id], params[:app_token])

    session[:podio_access_token] = Podio.client.oauth_token.access_token
    session[:podio_refresh_token] = Podio.client.oauth_token.refresh_token

    redirect_to root_url, :notice => "Signed in!"
  end

  def destroy
    session.clear
    redirect_to root_url, :notice => "Logged out!"
  end

end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController

  def index
    @tasks = Podio::Task.find_all(:responsible => 0, :completed => false) # 0 is a shortcut for current user
  end

  def show
    @task = Podio::Task.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>PodioRailsSample</title>
  <%= stylesheet_link_tag    "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leads/_form.html.erb
<p>
  <%= form.label :organization %>
  <%= form.text_field :organization %>
</p>
<p>
  <%= form.label :lead_contact %>
  <%= form.select :lead_contact, @lead_contacts.collect { |lc| [lc.name, lc.profile_id] } %>
</p>
<p>
  <%= form.label :sales_contact %>
  <%= form.select :sales_contact, @sales_contacts.collect { |lc| [lc.name, lc.profile_id] } %>
</p>
<p>
  <%= form.label :potential_revenue %>
  <%= form.text_field :potential_revenue_value %>
  <%= form.select :potential_revenue_currency, ['USD', 'EUR'] %>
</p>
<p>
  <%= form.label :probability %>
  <%= form.text_field :probability %>
</p>
<p>
  <%= form.label :status_id, 'Status' %>
  <%= form.select :status_id, @statuses %>
</p>
<p>
  <%= form.label :followup_at %>
  <%= form.date_select :followup_at %>
</p>

app/views/leads/edit.html.erb
<%= form_for :lead, :url => lead_path(@lead.id), :method => :put do |form| %>
  <%= render 'form', :form => form %>
  <%= form.submit 'Update Lead' %>
<% end %>

app/views/leads/index.html.erb
<table>
  <tr>
    <th>Organization</th>
    <th>Lead Contact</th>
    <th>Sales Contact</th>
    <th>Potential Revenue</th>
    <th>Probability</th>
    <th>Status</th>
    <th>Next follow up at</th>
    <th></th>
  </tr>
  <% for lead in @leads %>
    <tr>
      <td><%= lead.organization %></td>
      <td><%= lead.lead_contact %></td>
      <td><%= lead.sales_contact %></td>
      <td><%= number_to_currency(lead.potential_revenue_value, :unit => lead.potential_revenue_currency) %></td>
      <td><%= number_to_percentage(lead.probability.to_i) %></td>
      <td><%= lead.status_text %></td>
      <td><%= l(lead.followup_at.to_date) %></td>
      <td><%= link_to 'Edit', edit_lead_path(lead.id) %> | <%= link_to 'Delete', lead_path(lead.id), :method => :delete, :confirm => 'Are you sure?' %></td>
    </tr>
  <% end %>
</table>

<p>
  <%= link_to 'Create a new lead', new_lead_path %> |
  <%= link_to 'Show tasks', tasks_path %> |
  <%= link_to 'Logout', sessions_path, :method => :delete %>
</p>

app/views/leads/new.html.erb
<%= form_for :lead, :url => leads_path do |form| %>
  <%= render 'form', :form => form %>
  <%= form.submit 'Create Lead' %>
<% end %>

app/views/tasks/index.html.erb
<table>
  <tr>
    <th>Task ID</th>
    <th>Status</th>
    <th>Group</th>
    <th>Text</th>
    <th></th>
  </tr>
  <% for task in @tasks %>
    <tr>
      <td><%= task.id %></td>
      <td><%= task.status %></td>
      <td><%= task.group %></td>
      <td><%= task.text %></td>
      <td><%= link_to 'Details', task_path(task.id) %></td>
    </tr>
  <% end %>
</table>

<p><%= link_to 'Show leads', leads_path %> | <%= link_to 'Logout', sessions_path, :method => :delete %></p>

app/views/tasks/show.html.erb
<h1><%= @task.text %></h1>

<p>
  <strong>Status:</strong>
  <%= @task.status %>
</p>

<p>
  <strong>Group:</strong>
  <%= @task.group %>
</p>

<p>
  <strong>Decscription:</strong>
  <%= @task.description %>
</p>

<p>
  <strong>Due on:</strong>
  <%= @task.due_on %>
</p>

<p><%= link_to 'Show tasks', tasks_path %></p>